services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    # Use ephemeral storage to ensure queue is cleared on restart
    tmpfs:
      - /var/lib/rabbitmq

  rabbitmq-publisher:
    image: rabbitmq-publisher
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 10
      INITIAL_DELAY: 30
    depends_on:
      - rabbitmq

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - rabbitmq-publisher
