services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    # Use ephemeral storage to ensure queue is cleared on restart
    tmpfs:
      - /var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq-publisher:
    image: rabbitmq-publisher
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 10
      INITIAL_DELAY: 30
    depends_on:
      rabbitmq:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-publisher:
        condition: service_started
